// Static D&D 5e (2014) baseline data

import type { Ability, ClassData, Race } from "./types.ts";

export const races: Record<string, Race> = {
  Human: {
    subraces: ["Standard", "Variant"],
    bonuses: { STR: 1, DEX: 1, CON: 1, INT: 1, WIS: 1, CHA: 1 },
    speed: 30,
    traits: ["Extra Language"],
  },
  Elf: {
    subraces: ["High Elf", "Wood Elf", "Drow"],
    bonuses: { DEX: 2 },
    speed: 30,
    traits: ["Darkvision", "Keen Senses", "Fey Ancestry", "Trance"],
  },
  Dwarf: {
    subraces: ["Hill Dwarf", "Mountain Dwarf"],
    bonuses: { CON: 2 },
    speed: 25,
    traits: ["Darkvision", "Dwarven Resilience", "Dwarven Combat Training"],
  },
  Halfling: {
    subraces: ["Lightfoot", "Stout"],
    bonuses: { DEX: 2 },
    speed: 25,
    traits: ["Lucky", "Brave", "Halfling Nimbleness"],
  },
  Dragonborn: {
    subraces: [],
    bonuses: { STR: 2, CHA: 1 },
    speed: 30,
    traits: ["Draconic Ancestry", "Breath Weapon", "Damage Resistance"],
  },
  Gnome: {
    subraces: ["Forest Gnome", "Rock Gnome"],
    bonuses: { INT: 2 },
    speed: 25,
    traits: ["Darkvision", "Gnome Cunning"],
  },
  "Half-Elf": {
    subraces: [],
    bonuses: { CHA: 2 },
    speed: 30,
    traits: ["Darkvision", "Fey Ancestry", "Skill Versatility"],
  },
  "Half-Orc": {
    subraces: [],
    bonuses: { STR: 2, CON: 1 },
    speed: 30,
    traits: ["Darkvision", "Relentless Endurance", "Savage Attacks"],
  },
  Tiefling: {
    subraces: ["Asmodeus", "Baalzebul", "Dispater", "Mammon", "Mephistopheles"],
    bonuses: { INT: 1, CHA: 2 },
    speed: 30,
    traits: ["Darkvision", "Hellish Resistance", "Infernal Legacy"],
  },
};

export const subraceBonuses: Record<string, Partial<Record<Ability, number>>> =
  {
    "High Elf": { INT: 1 },
    "Wood Elf": { WIS: 1 },
    Drow: { CHA: 1 },
    "Hill Dwarf": { WIS: 1 },
    "Mountain Dwarf": { STR: 2 },
    Lightfoot: { CHA: 1 },
    Stout: { CON: 1 },
    "Forest Gnome": { DEX: 1 },
    "Rock Gnome": { CON: 1 },
  };

export const classes: Record<string, ClassData> = {
  Barbarian: {
    priority: ["STR", "CON", "DEX", "WIS", "CHA", "INT"],
    savingThrows: ["STR", "CON"],
    hitDie: 12,
    calling: "a fury-wreathed reaver",
  },
  Fighter: {
    priority: ["STR", "CON", "DEX", "WIS", "CHA", "INT"],
    savingThrows: ["STR", "CON"],
    hitDie: 10,
    calling: "a battle-tested champion",
  },
  Paladin: {
    priority: ["STR", "CHA", "CON", "WIS", "DEX", "INT"],
    savingThrows: ["WIS", "CHA"],
    hitDie: 10,
    calling: "a sworn guardian of a sacred oath",
  },
  Ranger: {
    priority: ["DEX", "WIS", "CON", "STR", "CHA", "INT"],
    savingThrows: ["STR", "DEX"],
    hitDie: 10,
    calling: "a tireless warden of the wild",
  },
  Rogue: {
    priority: ["DEX", "INT", "CON", "WIS", "CHA", "STR"],
    savingThrows: ["DEX", "INT"],
    hitDie: 8,
    calling: "a shadow-swift opportunist",
  },
  Monk: {
    priority: ["DEX", "WIS", "CON", "STR", "INT", "CHA"],
    savingThrows: ["STR", "DEX"],
    hitDie: 8,
    calling: "a disciplined master of body and spirit",
  },
  Bard: {
    priority: ["CHA", "DEX", "CON", "WIS", "INT", "STR"],
    savingThrows: ["DEX", "CHA"],
    hitDie: 8,
    calling: "a silver-tongued keeper of legends",
  },
  Sorcerer: {
    priority: ["CHA", "CON", "DEX", "WIS", "INT", "STR"],
    savingThrows: ["CON", "CHA"],
    hitDie: 6,
    calling: "a spellcaster born with dangerous power",
  },
  Warlock: {
    priority: ["CHA", "CON", "DEX", "WIS", "INT", "STR"],
    savingThrows: ["WIS", "CHA"],
    hitDie: 8,
    calling: "a pact-bound seeker of forbidden secrets",
  },
  Cleric: {
    priority: ["WIS", "STR", "CON", "CHA", "DEX", "INT"],
    savingThrows: ["WIS", "CHA"],
    hitDie: 8,
    calling: "a divine vessel carrying a god's will",
  },
  Druid: {
    priority: ["WIS", "CON", "DEX", "INT", "CHA", "STR"],
    savingThrows: ["INT", "WIS"],
    hitDie: 8,
    calling: "a shape-shifting voice of the wild",
  },
  Wizard: {
    priority: ["INT", "CON", "DEX", "WIS", "CHA", "STR"],
    savingThrows: ["INT", "WIS"],
    hitDie: 6,
    calling: "a scholar who bends reality through study",
  },
};

export const abilityNames: Ability[] = [
  "STR",
  "DEX",
  "CON",
  "INT",
  "WIS",
  "CHA",
];

export const abilityFullNames: Record<Ability, string> = {
  STR: "Strength",
  DEX: "Dexterity",
  CON: "Constitution",
  INT: "Intelligence",
  WIS: "Wisdom",
  CHA: "Charisma",
};

/** Chat-friendly aliases (abbreviation or full name) that resolve to a saving throw ability. */
export const abilityAliases: Record<string, Ability> = {
  str: "STR",
  strength: "STR",
  dex: "DEX",
  dexterity: "DEX",
  con: "CON",
  constitution: "CON",
  int: "INT",
  intelligence: "INT",
  wis: "WIS",
  wisdom: "WIS",
  cha: "CHA",
  charisma: "CHA",
};

/** Standard 5e skills and the ability score each is checked against. */
export const skillAbilities: Record<string, Ability> = {
  acrobatics: "DEX",
  "animal handling": "WIS",
  arcana: "INT",
  athletics: "STR",
  deception: "CHA",
  history: "INT",
  insight: "WIS",
  intimidation: "CHA",
  investigation: "INT",
  medicine: "WIS",
  nature: "INT",
  perception: "WIS",
  performance: "CHA",
  persuasion: "CHA",
  religion: "INT",
  "sleight of hand": "DEX",
  stealth: "DEX",
  survival: "WIS",
};

/** Solo monsters with numeric CR for level banding. */
export type SoloMonster = {
  name: string;
  cr: string;
  crValue: number;
  ac: number;
  hp: number;
  attack: number;
  die: number;
  bonus: number;
};

export const SOLO_MONSTERS: SoloMonster[] = [
  // CR 1/8 – 1/4 (levels ~1)
  {
    name: "Giant Rat",
    cr: "1/8",
    crValue: 0.125,
    ac: 12,
    hp: 7,
    attack: 4,
    die: 4,
    bonus: 2,
  },
  {
    name: "Stirge",
    cr: "1/8",
    crValue: 0.125,
    ac: 14,
    hp: 2,
    attack: 5,
    die: 4,
    bonus: 3,
  },
  {
    name: "Kobold Skirmisher",
    cr: "1/8",
    crValue: 0.125,
    ac: 12,
    hp: 5,
    attack: 4,
    die: 4,
    bonus: 2,
  },
  {
    name: "Goblin Scavenger",
    cr: "1/4",
    crValue: 0.25,
    ac: 15,
    hp: 7,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Skeleton Guard",
    cr: "1/4",
    crValue: 0.25,
    ac: 13,
    hp: 13,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Zombie Shambler",
    cr: "1/4",
    crValue: 0.25,
    ac: 8,
    hp: 22,
    attack: 3,
    die: 6,
    bonus: 1,
  },
  {
    name: "Wolf",
    cr: "1/4",
    crValue: 0.25,
    ac: 13,
    hp: 11,
    attack: 4,
    die: 4,
    bonus: 2,
  },
  {
    name: "Drow Scout",
    cr: "1/4",
    crValue: 0.25,
    ac: 15,
    hp: 13,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  // CR 1/2
  {
    name: "Wolf Pack Scout",
    cr: "1/2",
    crValue: 0.5,
    ac: 13,
    hp: 18,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Shadow",
    cr: "1/2",
    crValue: 0.5,
    ac: 12,
    hp: 16,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Cockatrice",
    cr: "1/2",
    crValue: 0.5,
    ac: 11,
    hp: 27,
    attack: 3,
    die: 4,
    bonus: 1,
  },
  {
    name: "Gnoll Hunter",
    cr: "1/2",
    crValue: 0.5,
    ac: 15,
    hp: 22,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Orc Raider",
    cr: "1/2",
    crValue: 0.5,
    ac: 13,
    hp: 15,
    attack: 5,
    die: 8,
    bonus: 3,
  },
  {
    name: "Thug",
    cr: "1/2",
    crValue: 0.5,
    ac: 11,
    hp: 32,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  // CR 1
  {
    name: "Dire Wolf",
    cr: "1",
    crValue: 1,
    ac: 14,
    hp: 37,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  {
    name: "Harpy",
    cr: "1",
    crValue: 1,
    ac: 11,
    hp: 38,
    attack: 3,
    die: 6,
    bonus: 1,
  },
  {
    name: "Imp",
    cr: "1",
    crValue: 1,
    ac: 13,
    hp: 10,
    attack: 5,
    die: 4,
    bonus: 3,
  },
  {
    name: "Quasit",
    cr: "1",
    crValue: 1,
    ac: 13,
    hp: 7,
    attack: 4,
    die: 4,
    bonus: 3,
  },
  {
    name: "Specter",
    cr: "1",
    crValue: 1,
    ac: 12,
    hp: 22,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Bugbear",
    cr: "1",
    crValue: 1,
    ac: 16,
    hp: 27,
    attack: 4,
    die: 8,
    bonus: 2,
  },
  {
    name: "Giant Spider",
    cr: "1",
    crValue: 1,
    ac: 14,
    hp: 26,
    attack: 5,
    die: 8,
    bonus: 3,
  },
  {
    name: "Yuan-ti Pureblood",
    cr: "1",
    crValue: 1,
    ac: 11,
    hp: 40,
    attack: 3,
    die: 6,
    bonus: 1,
  },
  // CR 2
  {
    name: "Ogre Brute",
    cr: "2",
    crValue: 2,
    ac: 11,
    hp: 59,
    attack: 6,
    die: 10,
    bonus: 4,
  },
  {
    name: "Gargoyle",
    cr: "2",
    crValue: 2,
    ac: 15,
    hp: 52,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Gelatinous Cube",
    cr: "2",
    crValue: 2,
    ac: 6,
    hp: 84,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Gibbering Mouther",
    cr: "2",
    crValue: 2,
    ac: 9,
    hp: 67,
    attack: 2,
    die: 6,
    bonus: 0,
  },
  {
    name: "Grick",
    cr: "2",
    crValue: 2,
    ac: 14,
    hp: 54,
    attack: 4,
    die: 8,
    bonus: 2,
  },
  {
    name: "Mimic",
    cr: "2",
    crValue: 2,
    ac: 12,
    hp: 58,
    attack: 5,
    die: 8,
    bonus: 3,
  },
  {
    name: "Will-o'-Wisp",
    cr: "2",
    crValue: 2,
    ac: 19,
    hp: 22,
    attack: 4,
    die: 8,
    bonus: 0,
  },
  {
    name: "Ettercap",
    cr: "2",
    crValue: 2,
    ac: 13,
    hp: 44,
    attack: 4,
    die: 8,
    bonus: 2,
  },
  // CR 3
  {
    name: "Owlbear",
    cr: "3",
    crValue: 3,
    ac: 13,
    hp: 59,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  {
    name: "Manticore",
    cr: "3",
    crValue: 3,
    ac: 14,
    hp: 68,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  {
    name: "Minotaur",
    cr: "3",
    crValue: 3,
    ac: 14,
    hp: 76,
    attack: 6,
    die: 12,
    bonus: 4,
  },
  {
    name: "Phase Spider",
    cr: "3",
    crValue: 3,
    ac: 13,
    hp: 32,
    attack: 4,
    die: 10,
    bonus: 2,
  },
  {
    name: "Werewolf",
    cr: "3",
    crValue: 3,
    ac: 12,
    hp: 58,
    attack: 4,
    die: 8,
    bonus: 2,
  },
  {
    name: "Wight",
    cr: "3",
    crValue: 3,
    ac: 14,
    hp: 45,
    attack: 4,
    die: 6,
    bonus: 2,
  },
  {
    name: "Basilisk",
    cr: "3",
    crValue: 3,
    ac: 15,
    hp: 52,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  {
    name: "Displacer Beast",
    cr: "3",
    crValue: 3,
    ac: 13,
    hp: 85,
    attack: 6,
    die: 6,
    bonus: 4,
  },
  // CR 4
  {
    name: "Ettin",
    cr: "4",
    crValue: 4,
    ac: 12,
    hp: 85,
    attack: 7,
    die: 8,
    bonus: 5,
  },
  {
    name: "Black Pudding",
    cr: "4",
    crValue: 4,
    ac: 7,
    hp: 85,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  {
    name: "Couatl",
    cr: "4",
    crValue: 4,
    ac: 16,
    hp: 97,
    attack: 8,
    die: 6,
    bonus: 5,
  },
  {
    name: "Elephant",
    cr: "4",
    crValue: 4,
    ac: 12,
    hp: 76,
    attack: 8,
    die: 8,
    bonus: 5,
  },
  {
    name: "Ghost",
    cr: "4",
    crValue: 4,
    ac: 11,
    hp: 45,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  {
    name: "Lamia",
    cr: "4",
    crValue: 4,
    ac: 13,
    hp: 97,
    attack: 5,
    die: 10,
    bonus: 3,
  },
  {
    name: "Red Dragon Wyrmling",
    cr: "4",
    crValue: 4,
    ac: 17,
    hp: 75,
    attack: 6,
    die: 10,
    bonus: 4,
  },
  {
    name: "Succubus",
    cr: "4",
    crValue: 4,
    ac: 15,
    hp: 66,
    attack: 5,
    die: 6,
    bonus: 3,
  },
  // CR 5
  {
    name: "Troll",
    cr: "5",
    crValue: 5,
    ac: 15,
    hp: 84,
    attack: 7,
    die: 6,
    bonus: 4,
  },
  {
    name: "Young Dragon",
    cr: "5",
    crValue: 5,
    ac: 17,
    hp: 75,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  {
    name: "Bulette",
    cr: "5",
    crValue: 5,
    ac: 17,
    hp: 94,
    attack: 7,
    die: 12,
    bonus: 4,
  },
  {
    name: "Elemental Earth",
    cr: "5",
    crValue: 5,
    ac: 17,
    hp: 126,
    attack: 8,
    die: 8,
    bonus: 5,
  },
  {
    name: "Flesh Golem",
    cr: "5",
    crValue: 5,
    ac: 9,
    hp: 93,
    attack: 7,
    die: 8,
    bonus: 4,
  },
  {
    name: "Hill Giant Scout",
    cr: "5",
    crValue: 5,
    ac: 13,
    hp: 105,
    attack: 8,
    die: 10,
    bonus: 5,
  },
  {
    name: "Night Hag",
    cr: "5",
    crValue: 5,
    ac: 17,
    hp: 112,
    attack: 7,
    die: 8,
    bonus: 4,
  },
  {
    name: "Shambling Mound",
    cr: "5",
    crValue: 5,
    ac: 15,
    hp: 136,
    attack: 7,
    die: 8,
    bonus: 4,
  },
  {
    name: "Unicorn",
    cr: "5",
    crValue: 5,
    ac: 12,
    hp: 67,
    attack: 7,
    die: 8,
    bonus: 4,
  },
  {
    name: "Vampire Spawn",
    cr: "5",
    crValue: 5,
    ac: 15,
    hp: 82,
    attack: 6,
    die: 6,
    bonus: 3,
  },
  // CR 6
  {
    name: "Hill Giant",
    cr: "6",
    crValue: 6,
    ac: 13,
    hp: 105,
    attack: 8,
    die: 10,
    bonus: 5,
  },
  {
    name: "Mammoth",
    cr: "6",
    crValue: 6,
    ac: 13,
    hp: 126,
    attack: 10,
    die: 10,
    bonus: 7,
  },
  {
    name: "Medusa",
    cr: "6",
    crValue: 6,
    ac: 15,
    hp: 127,
    attack: 5,
    die: 6,
    bonus: 2,
  },
  {
    name: "Cyclops",
    cr: "6",
    crValue: 6,
    ac: 14,
    hp: 138,
    attack: 9,
    die: 10,
    bonus: 6,
  },
  {
    name: "Wyvern",
    cr: "6",
    crValue: 6,
    ac: 13,
    hp: 110,
    attack: 7,
    die: 6,
    bonus: 4,
  },
  {
    name: "Young White Dragon",
    cr: "6",
    crValue: 6,
    ac: 17,
    hp: 133,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  // CR 7
  {
    name: "Chimera",
    cr: "7",
    crValue: 7,
    ac: 14,
    hp: 114,
    attack: 8,
    die: 10,
    bonus: 4,
  },
  {
    name: "Giant Ape",
    cr: "7",
    crValue: 7,
    ac: 12,
    hp: 157,
    attack: 9,
    die: 10,
    bonus: 6,
  },
  {
    name: "Oni",
    cr: "7",
    crValue: 7,
    ac: 16,
    hp: 110,
    attack: 7,
    die: 8,
    bonus: 4,
  },
  {
    name: "Shield Guardian",
    cr: "7",
    crValue: 7,
    ac: 17,
    hp: 142,
    attack: 7,
    die: 6,
    bonus: 4,
  },
  {
    name: "Stone Giant",
    cr: "7",
    crValue: 7,
    ac: 17,
    hp: 126,
    attack: 9,
    die: 8,
    bonus: 6,
  },
  {
    name: "Young Black Dragon",
    cr: "7",
    crValue: 7,
    ac: 18,
    hp: 127,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  // CR 8
  {
    name: "Frost Giant",
    cr: "8",
    crValue: 8,
    ac: 15,
    hp: 138,
    attack: 9,
    die: 12,
    bonus: 6,
  },
  {
    name: "Fomorian",
    cr: "8",
    crValue: 8,
    ac: 14,
    hp: 149,
    attack: 9,
    die: 8,
    bonus: 6,
  },
  {
    name: "Hydra (young)",
    cr: "8",
    crValue: 8,
    ac: 15,
    hp: 172,
    attack: 8,
    die: 10,
    bonus: 5,
  },
  {
    name: "Tyrannosaurus Rex",
    cr: "8",
    crValue: 8,
    ac: 13,
    hp: 136,
    attack: 10,
    die: 12,
    bonus: 7,
  },
  {
    name: "Young Green Dragon",
    cr: "8",
    crValue: 8,
    ac: 18,
    hp: 136,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  {
    name: "Mind Flayer",
    cr: "8",
    crValue: 8,
    ac: 15,
    hp: 71,
    attack: 7,
    die: 10,
    bonus: 4,
  },
  // CR 9
  {
    name: "Fire Giant",
    cr: "9",
    crValue: 9,
    ac: 18,
    hp: 162,
    attack: 10,
    die: 10,
    bonus: 7,
  },
  {
    name: "Cloud Giant",
    cr: "9",
    crValue: 9,
    ac: 14,
    hp: 200,
    attack: 12,
    die: 12,
    bonus: 8,
  },
  {
    name: "Glabrezu",
    cr: "9",
    crValue: 9,
    ac: 17,
    hp: 157,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  {
    name: "Young Blue Dragon",
    cr: "9",
    crValue: 9,
    ac: 18,
    hp: 152,
    attack: 9,
    die: 10,
    bonus: 5,
  },
  {
    name: "Treant",
    cr: "9",
    crValue: 9,
    ac: 16,
    hp: 138,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  // CR 10
  {
    name: "Stone Golem",
    cr: "10",
    crValue: 10,
    ac: 17,
    hp: 178,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  {
    name: "Aboleth",
    cr: "10",
    crValue: 10,
    ac: 17,
    hp: 135,
    attack: 9,
    die: 6,
    bonus: 5,
  },
  {
    name: "Deva",
    cr: "10",
    crValue: 10,
    ac: 17,
    hp: 136,
    attack: 8,
    die: 6,
    bonus: 4,
  },
  {
    name: "Guardian Naga",
    cr: "10",
    crValue: 10,
    ac: 18,
    hp: 127,
    attack: 8,
    die: 8,
    bonus: 4,
  },
  {
    name: "Young Red Dragon",
    cr: "10",
    crValue: 10,
    ac: 18,
    hp: 178,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  {
    name: "Death Slaad",
    cr: "10",
    crValue: 10,
    ac: 18,
    hp: 170,
    attack: 9,
    die: 10,
    bonus: 5,
  },
  // CR 11
  {
    name: "Behir",
    cr: "11",
    crValue: 11,
    ac: 17,
    hp: 168,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  {
    name: "Horned Devil",
    cr: "11",
    crValue: 11,
    ac: 18,
    hp: 178,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  {
    name: "Remorhaz",
    cr: "11",
    crValue: 11,
    ac: 17,
    hp: 195,
    attack: 11,
    die: 10,
    bonus: 7,
  },
  {
    name: "Roc",
    cr: "11",
    crValue: 11,
    ac: 15,
    hp: 248,
    attack: 13,
    die: 10,
    bonus: 9,
  },
  {
    name: "Efreeti",
    cr: "11",
    crValue: 11,
    ac: 17,
    hp: 200,
    attack: 10,
    die: 10,
    bonus: 6,
  },
  // CR 12
  {
    name: "Adult Dragon Wyrmling-Guard",
    cr: "12",
    crValue: 12,
    ac: 18,
    hp: 200,
    attack: 11,
    die: 12,
    bonus: 7,
  },
  {
    name: "Archmage Shade",
    cr: "12",
    crValue: 12,
    ac: 15,
    hp: 99,
    attack: 6,
    die: 8,
    bonus: 2,
  },
  {
    name: "Erinyes",
    cr: "12",
    crValue: 12,
    ac: 18,
    hp: 153,
    attack: 8,
    die: 8,
    bonus: 4,
  },
  {
    name: "Kraken Spawn",
    cr: "12",
    crValue: 12,
    ac: 16,
    hp: 230,
    attack: 12,
    die: 10,
    bonus: 8,
  },
  {
    name: "Purple Worm Juvenile",
    cr: "12",
    crValue: 12,
    ac: 18,
    hp: 220,
    attack: 12,
    die: 12,
    bonus: 8,
  },
];

/**
 * Pick a monster appropriate for the player's level.
 * Tuned so solo heroes win often at low level, but face a genuinely losable
 * fight at high level — not a guaranteed win.
 */
export function pickMonsterForLevel(level: number): SoloMonster {
  const lv = Math.max(1, Math.min(20, Math.floor(level || 1)));
  // Softer curve than true 5e deadly encounters — stream-friendly.
  // L1 → ~0.25–0.5 | L4 → ~1 | L8 → ~2 | L12 → ~3.5 | L20 → ~5.5
  const targetCr = Math.max(0.125, Math.min(10, (lv + 1) / 4));
  const minCr = 0.125;
  const maxCr = Math.min(12, targetCr * 1.25 + 0.25);

  let pool = SOLO_MONSTERS.filter((m) =>
    m.crValue >= minCr && m.crValue <= maxCr
  );
  if (!pool.length) {
    pool = [...SOLO_MONSTERS]
      .sort((a, b) =>
        Math.abs(a.crValue - targetCr) - Math.abs(b.crValue - targetCr)
      )
      .slice(0, 5);
  }

  // Weight toward monsters at or below target CR (easier wins more often).
  const weights = pool.map((m) => {
    if (m.crValue <= targetCr) return 3;
    if (m.crValue <= targetCr * 1.15) return 1.2;
    return 0.4;
  });
  const totalW = weights.reduce((a, b) => a + b, 0);
  let roll = Math.random() * totalW;
  let base = pool[0];
  for (let i = 0; i < pool.length; i++) {
    roll -= weights[i];
    if (roll <= 0) {
      base = pool[i];
      break;
    }
  }

  // Player-favoring scale — but the growth now tracks how much the PLAYER's
  // own combat math grows with level (proficiency feeds both their to-hit
  // and their AC in combat.ts; their ability modifier is fixed at creation
  // and doesn't grow further). The old flat multipliers here (attack *0.9 +
  // (lv-1)*0.08, ac capped at 18) grew far slower than the player's
  // proficiency, so by roughly level 5 the character's to-hit and AC had
  // already outpaced them — solo duels simulated out to a ~99–100% player
  // win rate from level 5 through 20, i.e. functionally unloseable despite
  // the table picking higher-CR monsters at higher levels. `growth` ramps
  // smoothly from 0 at level 1 to 1 at level 20 so early fights stay
  // forgiving while high-level ones are a real, losable fight (~90% win
  // rate at L1 tapering to ~65% at L20 in simulation).
  const growth = (lv - 1) / 19; // 0 at L1 → 1 at L20
  const hpScale = 0.8 + growth * 0.5; // ~0.80–1.30
  return {
    ...base,
    hp: Math.max(6, Math.round(base.hp * hpScale)),
    attack: Math.max(2, Math.round(base.attack * 1.1 + growth * 7.5)),
    bonus: Math.max(0, Math.round(base.bonus * 1.1 + growth * 4.2)),
    ac: Math.min(24, Math.max(10, Math.round(base.ac + 2.5 + growth * 9))),
  };
}

export const knownBotAccounts = new Set([
  "nightbot",
  "streamelements",
  "streamlabs",
  "moobot",
  "fossabot",
  "wizebot",
  "deepbot",
  "coebot",
  "ankhbot",
]);

export const lookupResources: Record<string, string> = {
  spell: "spells",
  item: "equipment",
  class: "classes",
  feat: "feats",
  ability: "ability-scores",
  race: "races",
  subrace: "subraces",
  rule: "rule-sections",
  rules: "rule-sections",
  monster: "monsters",
};

export const MAX_LOOKUP_MESSAGE_LENGTH = 300;