// Guild Codex section for the Hunt and Hoard module (hoard.ts). Its own file
// to keep guide_arena.ts under Val Town's per-file size ceiling; guide.ts
// splices it in right after "Arena, wilds & the company".

const switchLink = (key: string, label: string) =>
  `<a class="switch-link" href="/dashboard/go?toggle=${key}" title="Mods: jump to this card's on/off switch on your channel dashboard">⚙ Dashboard switch: ${label}</a>`;

export const GUIDE_HOARD_HTML = `<h2 id="hoard">Hunt and Hoard</h2><p>The Wandering Clerk's hunting-and-shopping game, played with your GuildScribe character. Hunt the channel's bestiary for XP and loot, fill bounties, and spend your coin at the stall. Unlike a <code>!dndduel</code> hunt, <strong>your HP carries over between hunts</strong> — rest or drink potions to keep going. Off until a mod opens it.</p><div class="grid">` +
  `<section class="card" id="card-hoard"><h3>Open the module (mod/broadcaster)</h3>${switchLink("hoard", "Hunt and Hoard")}<span class="cmd">!hoard on</span><span class="cmd">!hoard off</span><span class="cmd">!hoard status</span><span class="cmd">!hoard</span><p><strong>Off by default.</strong> <code>on</code>/<code>off</code> are mod/broadcaster; <code>status</code> is open to everyone. Bare <code>!hoard</code> shows your sheet and a <em>Next:</em> hint for what to do. Closing it keeps everyone's potions and bounty progress. If the channel already has its own custom command called <code>!shop</code>, <code>!buy</code> or similar, that custom command keeps answering instead.</p></section>` +
  `<section class="card" id="card-hoardhunt"><h3>Hunting</h3>${switchLink("hoardhunt", "Hunting")}<span class="cmd">!hunt</span><span class="cmd">!hunt &lt;monster&gt;</span><span class="cmd">!rest</span><span class="cmd">!ledger</span><span class="cmd">!ledger @username</span><p><code>!hunt</code> sends your character after a level-appropriate monster from the channel's <a href="#card-bestiary">bestiary</a> (or a named one). It uses the same fight engine, monster scaling, adaptation, XP, coin loot and hunting cooldown as <code>!dndduel</code> — but the fight starts at your <em>current</em> HP and leaves you wherever it ended (never below 1 HP). At 1 HP you must heal first.</p><p><code>!rest</code> recovers you to 80% of max HP. You also regain 3 HP every 15 minutes on your own. <code>!ledger</code> shows a hero's level, HP, AC, XP, coin, potions and gear.</p></section>` +
  `<section class="card" id="card-hoardbounties"><h3>Bounty board</h3>${switchLink("hoardbounties", "Bounty board")}<span class="cmd">!bounties</span><span class="cmd">!quests</span><p>Three postings like "slay 4 Goblins", drawn from the easy end of the bestiary (CR 3 or lower). Kills from <code>!hunt</code> and <code>!autohunt</code> count toward them. Progress is your own, but the board is shared: whoever finishes a posting first collects the coin (and sometimes a potion), and a new posting replaces it. The whole board is reposted every 30 minutes.</p></section>` +
  `<section class="card" id="card-hoardshop"><h3>Stall &amp; pack</h3>${switchLink("hoardshop", "Stall & pack")}<span class="cmd">!shop</span><span class="cmd">!shop &lt;#|name&gt;</span><span class="cmd">!buy &lt;#|name&gt;</span><span class="cmd">!inv</span><span class="cmd">!use &lt;potion&gt;</span><span class="cmd">!sell &lt;potion&gt;</span><span class="cmd">!drop &lt;potion&gt;</span><span class="cmd">!purse</span><p>The stall has three wares: healing potions and the peddler's gear (rarely, a legendary relic). It turns over every 20 minutes, and a sold slot restocks at once. <code>!shop 2</code> shows one ware's details and a bit of lore. Prices are real coin (<a href="#gold">gold</a> must be on).</p><p>Gear goes straight onto your character sheet as a permanent bonus, the same as a <a href="#card-haggle"><code>!haggle</code></a> purchase, so it counts in every fight. Potions go in your pack: <code>!use</code> heals you, <code>!sell</code> returns half the price. <code>!purse</code> shows your coin and what it can buy.</p></section>` +
  `</div><p class="muted">Not using Hunt and Hoard? <code>!autohunt</code>, <code>!dndduel</code> and raids work exactly as before and ignore its HP.</p>`;
