// Chat text for `!dndbothelp <chapter>`.
//
// Lives in its own module because Val Town refuses to push a file that is too
// large and main.ts had grown to the edge of that limit. Pure data: no imports,
// no side effects. `category` is the lowercased word after !dndbothelp (or
// undefined for the bare command, which lists the chapters).

export function chatHelpText(category: string | undefined, publicBaseUrl: string): string {
  return (
    category === "dice"
      ? "🎲 Fate's dice: !d20 | !d20 @user | !roll | !r | !roll NdS[+/-M] (e.g. !roll 2d6+3) | !roll @user [NdS[+/-M]] | !save <ability> saving throw vs the bot's d20 + the raid boss's save bonus (e.g. !save dex, or !save dex dc15 against a DC) | !save [@user] [+mods] to roll 1d20 (+ e.g. +3 or +1d4) against the bot's d20 — beat or tie it to win; @user makes them roll the save | !saves for this stream's saving throws tally (!saves reset, mod) | !roll <skill> check (e.g. !roll stealth) — uses your saved character | !roll <question>? for a D&D-flavored yes/no verdict (e.g. !roll is enya going to die this time?) | !rollcall [nat1/nat20] [hour/day/week] for the natural 1/20 leaderboard, or !rollcall @user [hour/day/week] for one player's own nat1/nat20 counts | !oracle <question> for the oracle to name a random recent chatter as the answer (e.g. !oracle who should stream next?) | !bg3roll for a random Baldur's Gate 3 style character | !bg3companion for a random BG3 companion match | !bg3origin to be cast as a random Origin Character | !bg3loot for a random BG3-style magic item drop | !bg3camp for a random camp-night vignette"
      : category === "settings"
        ? "🏛️ Guild stewards (mod/broadcaster): !dndbot on | !dndbot off | !dndbot status | !dndbot leave [purge] | !market on | !market off | !market status (off by default) | !autoban on | !autoban off | !autoban status (off by default — permanently bans non-mods who use a phrase on the auto-ban list, e.g. \"ai viewers\"; edit it from !dashboard) | !hoard on | !hoard off | !hoard status (Hunt and Hoard: !hunt, !bounties, !shop — off by default) | !ball on | !ball off | !ball status (suggests a ball when PokemonCommunityGame spawns a Pokémon; teach it new balls on !dashboard → 🔴 Pokéballs — off by default) | !gold on | !gold off | !gold status (coin, leaderboard, giveaways & paid !haggle — on by default) | !checklist [add <item> | remove <n> | clear | on | off | status] (stream checklist, sent to the broadcaster when the stream goes live if it has items — off by default) | !help | !guide | !link"
        : category === "character"
          ? "⚔️ Adventurer's parchment: !createchar | !createchar @user (mod) | !newchar | !bg3 (random race/class, you choose BG3 point-buy scores) | !answer <choice> | !cancel | !char | !char @user | !abilities [@user] (combat abilities) | !roster (link to a web page of every adventurer, party and party member) | !levelup [@user] [+/-N] (mod) | !hp [+/-N] | !savechar | !loadchar | !resetchar | !resetchar @user (mod) | !shmash [@user] for a purely-for-fun narrated smash using your character (no HP/game state touched) | !watchtime [@user] for how long someone has been around while the stream is live | !followage [@user] for how long someone has followed the channel"
          : category === "party"
            ? "🛡️ Guild company: !party create <name> | !party join <name> | !party invite @user [name] | !party accept/decline [name] | !party list [name] (roster + members) | !roster (web page of every party and its members) | !party leave <name> | !party disband <name>"
            : category === "combat"
              ? "⚔️ Arena & wilds: !bestiary (web list of every huntable monster) | !bestiary <monster> | !bestiary learn <monster> | !bestiary forget/reset <monster> (mod) | !dndduel @user (auto) | !dndduel classic @user | !dndduel accept/decline/attack/status/end | !dndduel [monster] (auto) | !dndduel monster [classic] [monster] | !dndduel party A B | !dndduel party classic A B | !dndduel party accept/decline/attack/status/end | !dndduel party hunt <party> [monster] | !dndduel party hunt classic <party> [monster] | !dndduel party hunt attack/status/end (also !party hunt …) | !autohunt [20m|1h] (send your hero hunting on a timer; 5 min per bout, default 15m) | !autohunt status | !autohunt stop | !rally (this stream's raid boss: sound the horn or join the party) | !rally go | !rally status | !rally cooldown [time|off] (mod sets) | !rally new (mod) | !huntcooldown (shows the hunting cooldown shared by solo hunts, party hunts and autohunt; mods set it with !huntcooldown <90s|5m|off>) | !turn start | !turn roll | !turn add <name> <init> | !turn show | !turn next | !turn prev | !turn remove <name> | !turn end | !rob @user (your characters duel; the loser pays the winner 1-9% of their coin — needs coin on, see !dndbothelp gold) | Slaying a monster (solo or on a hunt) also drops a little coin, split among surviving hunters"
              : category === "lookup"
                ? "📚 Guild archives: !spell <name> [+N] | !item <name> [+N] | !class <name> | !feat <name> | !ability <score> | !race <name> | !subrace <name> | !monster <name> (teaches the bestiary new monsters) | !rule <topic> | !rules <topic> (e.g. !spell fireball, !rules magic, !monster goblin) | !bg3lookup <name> — BG3 companions/origins/classes/races/locations/factions/deities/villains/items (e.g. !bg3lookup astarion, !bg3lookup moonrise towers)"
                : category === "maps"
                  ? "🗺️ Battle maps: !map create <name> [WxH] [template] (mod) | !map templates | !map list | !map view <name> | !map delete <name> / !map remove <name> (mod) | !map terrains | !map fill <name> <terrain> (mod) | !map paint <name> <x> <y> <terrain> (mod) | !map addchar <name> [x y] | !map addchar <name> @user [x y] (mod) | !map move <name> <x> <y> | !map move <name> @user <x> <y> (mod) | !map removechar <name> [@user]"
                  : category === "gold"
                    ? "💰 Coin & giveaways (on by default — mods can switch off with !gold off): chat and slay monsters (solo or on hunts) while the stream is live to earn copper — nothing is earned offline; 10 cp = 1 sp, 10 sp = 1 gp; amounts like 50, 5sp, 1gp, 1gp 2sp | !gold (your purse + rank) | !gold @user | !gold top [N] / !goldboard (richest adventurers) | !gold give @user <amount> | !gold add/remove/set @user <amount> (mod) | !gold on/off/status | !giveaway (status) | !giveaway enter [tickets] | !giveaway start [cost=<amount>] [max=N] <prize> (mod) | !giveaway draw / reroll / cancel (mod) | !rob @user — duel their character; the loser pays the winner a random 1-9% of their coin | !haggle <pitch> — the peddler's coin prices are real, a deal is paid on the spot, a refusal is free (attacking or robbing the peddler always fails, and chat will laugh) | !jar — the swear jar total and its last giveaway (swearing in chat costs 2 cp each, paid from your gold) | !jar +<amount> add by hand | !jar +<amount> @user fine someone, paid from their gold (mod) | !jar -<amount> take out (mod) | !jar words / !jar forget <word> — see or veto words the jar learned from chat (mod) | !jar giveaway — give the whole jar to a random recent chatter, once per 7 days (mod) | !fine — fine the streamer one swear word (anyone) | !stall — see what the peddler is selling and your haggle attempts left | !gear [@user] — peddler wares on a character sheet (each one you buy boosts your stats) | !gear list — web list of every ware and who carries it | Channel-point rewards: !boon status [@user] | !boon list | !boon add shield|lockout <minutes> <reward title> (mod) | !boon remove <title> (mod) | !boon clear @user (mod) — a shield stops !rob on you; a lockout (viewer types \"<user> <feature>\") blocks someone from a feature for a while"
                  : category === "custom"
                    ? "🛠️ Custom commands & triggers: !dndbot add <name> <response> | !dndbot edit <name> <response> | !dndbot remove <name> | !dndbot cooldown <name> <seconds> | !dndbot enable/disable <name> | !dndbot list | !trigger add <keyword> <response> | !trigger remove <keyword> | !trigger cooldown <keyword> <seconds> | !trigger enable/disable <keyword> | !trigger list | !timedmsg add <minutes> <message> | !timedmsg edit <id> <message> | !timedmsg interval <id> <minutes> | !timedmsg enable/disable <id> | !timedmsg remove <id> | !timedmsg list | !dashboard [reset] (mod) get a web link to manage all of these — add/edit/remove/cooldown/interval/enable/disable are mod-only, list is open to everyone"
                    : `📜 Guild Codex chapters: dice | character | party | combat | lookup | maps | gold | custom | settings. Example: !dndbothelp party — full book: ${publicBaseUrl}/guide`
  );
}
