// Flavor lines for duels, hunts and fights (duelNarration).
// Split out of utils.ts to keep every file well under Val Town's per-file
// size ceiling.

import { pick } from "./utils.ts";

export function duelNarration(stage: string) {
  const lines: Record<string, string[]> = {
    challenge: [
      "The arena gates swing open.",
      "The gauntlet has been thrown.",
      "Fate calls for a showdown.",
      "A challenge echoes through the tavern.",
      "The bards ready their instruments—this could be a good one.",
      "Steel is drawn before a word is spoken.",
      "The crowd senses blood in the air.",
      "A dare no adventurer could refuse.",
      "The dice are already whispering about this one.",
      "Someone just signed up for a legendary tale.",
      "The tavern falls silent, waiting.",
      "A rivalry is about to be settled the old-fashioned way.",
      "The DM reaches for the initiative tracker.",
      "Honor, glory, and bragging rights are on the line.",
      "The challenge horn sounds across the guild hall.",
      "Two adventurers, one arena, zero mercy.",
      "The gauntlet lands with a satisfying thud.",
      "A duel is declared, and the crowd gathers 'round.",
      "The stakes have been set—glory or the ground.",
      "Fate shuffles its deck for this one.",
    ],
    accept: [
      "The crowd roars—the duel is on.",
      "Steel meets destiny.",
      "The initiative gods have been consulted.",
      "Acceptance granted—may the bones favor the bold.",
      "The gauntlet is picked up without hesitation.",
      "Both sides square off beneath torchlight.",
      "The bard starts composing before the first swing.",
      "A nod, a grip on the hilt, and it begins.",
      "The tavern clears a space for the coming chaos.",
      "Challenge accepted—the dice are drawn.",
      "The arena gates seal shut behind them.",
      "No turning back now; the die is cast.",
      "Two hearts race to the same drumbeat.",
      "The DM smiles—always a bad sign.",
      "Weapons are drawn, and so is everyone's attention.",
      "The duel begins under a watchful moon.",
      "Fate nods its approval.",
      "The crowd chants for first blood.",
      "Initiative rolled, tension rising.",
      "The challenge is met in full.",
    ],
    decline: [
      "The challenge fades into the tavern gossip.",
      "Wisdom wins this round.",
      "The duel is postponed by fate.",
      "Discretion proves the better part of valor.",
      "The gauntlet is left lying in the dirt.",
      "A tactical retreat, disguised as good sense.",
      "The bard shrugs and writes a different song.",
      "Not every quest needs to be accepted.",
      "The crowd grumbles but respects the choice.",
      "Sometimes the wisest roll is walking away.",
      "The challenge is filed under 'maybe later.'",
      "Even heroes pick their battles.",
      "The arena stays quiet a little longer.",
      "A polite decline, sword still sheathed.",
      "The duel dissolves back into idle chatter.",
      "Better a live coward than a dead hero, some say.",
      "The gauntlet is returned, unthrown.",
      "The DM shrugs and moves the plot along.",
      "Peace prevails, for now.",
      "The tavern returns to its usual roar.",
    ],
    hit: [
      "A clean strike finds its mark.",
      "That hit had advantage from destiny.",
      "The dice have chosen violence.",
      "Steel sings true.",
      "A textbook strike, straight from the manual.",
      "The blade finds its mark without mercy.",
      "That connected with authority.",
      "A solid hit—the crowd cheers.",
      "The attack lands clean and true.",
      "Fortune favors the aim this time.",
      "The strike lands with a satisfying crunch.",
      "A well-placed hit, worthy of a bard's verse.",
      "The blow connects, no saving throw in sight.",
      "That's going straight into the campaign log.",
      "A precise, punishing hit.",
      "The attack roll clears the armor class with room to spare.",
      "Contact made—and it hurt.",
      "The strike lands like it was scripted.",
      "A hit worthy of a highlight reel.",
      "The dice roll high, and the blade follows through.",
    ],
    miss: [
      "The attack misses wide; the boots remain unharmed.",
      "The blade finds only air.",
      "The dice requested a dramatic near miss.",
      "A swing and a whiff.",
      "The attack sails past, dramatically unthreatening.",
      "Armor class wins this exchange.",
      "The strike goes wide, to the crowd's disappointment.",
      "That one's going in the blooper reel.",
      "A valiant effort, poorly aimed.",
      "The dice roll low, and the blow follows suit.",
      "The attack misses by the length of a goblin's nose.",
      "Nothing but air and bruised pride.",
      "The blade whistles past, missing entirely.",
      "A near miss, emphasis on the miss.",
      "The strike lands nowhere useful.",
      "Fortune looks away for this swing.",
      "The attack fumbles its footing.",
      "A miss so clean it's almost impressive.",
      "The blow glances off nothing at all.",
      "That roll needed a little more luck.",
    ],
    critical: [
      "A critical hit! The bards are taking notes.",
      "Natural twenty—legendary timing.",
      "The D20 of Fate has opened the vault.",
      "A critical strike worthy of legend.",
      "The crowd loses its collective mind.",
      "That's a nat 20 if there ever was one.",
      "Critical! Somewhere, a bard just found their next verse.",
      "The dice have crowned a champion—for this round.",
      "A perfect strike, straight out of a campaign highlight.",
      "The heavens themselves seem to approve of that roll.",
      "Critical hit! The dungeon master allows a dramatic pause.",
      "That roll belongs in the guild's hall of fame.",
      "A devastating critical—someone's taking damage rolls twice.",
      "The natural 20 gods have smiled upon this strike.",
      "Critical! Even the monster looks impressed.",
      "A flawless strike for the ages.",
      "The dice landed on legendary.",
      "That's the kind of hit sequels are made of.",
      "Critical success—roll for damage, roll for glory.",
      "The stars aligned for that swing.",
    ],
    defeat: [
      "A character falls, but the story continues.",
      "The HP bar has entered the underworld.",
      "A dramatic collapse worthy of the final act.",
      "Zero HP, maximum drama.",
      "The fallen adventurer earns a moment of respectful silence.",
      "Down, but the campaign marches on.",
      "A defeat worthy of its own tragic ballad.",
      "The dice were not merciful this time.",
      "The battlefield claims another combatant.",
      "A hard-fought loss, and a story for the tavern.",
      "The final blow lands, and the duel ends.",
      "Down goes the challenger—someone alert the healer.",
      "The HP counter hits zero with theatrical timing.",
      "A noble defeat, recorded in the guild log.",
      "The fight ends, one combatant left standing.",
      "The loser limps off to nurse their pride.",
      "That's a wipe—time to regroup at camp.",
      "The dice have spoken, and the answer was defeat.",
      "A fall worthy of the campaign's next flashback.",
      "The duel closes with one combatant down for the count.",
    ],
    victory: [
      "Victory belongs to the last character standing.",
      "The winner claims the tavern bragging rights.",
      "The campaign chronicle gains a new legend.",
      "Victory! The bards are already rehearsing.",
      "The guild hall erupts in cheers.",
      "A win worthy of its own chapter.",
      "The victor raises their weapon to a roaring crowd.",
      "Glory secured, one HP bar at a time.",
      "The champion stands, the dust settles.",
      "A hard-won victory, exactly the kind bards love.",
      "The dice crowned a winner tonight.",
      "Victory earned—the tavern's buying the next round.",
      "The last one standing takes the spoils.",
      "A triumphant finish worthy of the campaign log.",
      "The winner's name goes up on the guild board.",
      "Another legend added to the chronicle.",
      "The battle ends, and glory is claimed.",
      "Victory! Somewhere, a bard just got a new song idea.",
      "The champion emerges, battered but triumphant.",
      "The dust clears, and one hero remains.",
    ],
  };
  const pool = lines[stage] ?? lines.hit;
  return pool[Math.floor(Math.random() * pool.length)];
}
